# Generated by Django 5.0.4 on 2024-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('jundice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25)),
                ('usedscreeningbefore', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('whoistakingtest', models.CharField(choices=[('Self', 'Self'), ('Parent', 'Parent'), ('Health care professional', 'Health care professional'), ('Relative', 'Relative'), ('Other', 'Other')], max_length=25)),
                ('q1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q6', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q7', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q8', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q9', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('q10', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
            ],
        ),
    ]
